---
title: "Lecture script"
date: "May 27th 2020"
output: html_document
---


```{r}
library(AER)
data("Fatalities")

dat.fat=Fatalities

y=dat.fat$fatal;
X=as.matrix(dat.fat[,c('spirits','unemp','income','beertax','baptist','mormon','drinkage','dry','youngdrivers','miles','gsp')])

linear.model<-function(beta,covariate){
  # beta: a 2-vector, where the first entry is the intercept
  yout=covariate*beta[2]+beta[1]
  return(yout);
  # Note: this function only works with simple linear regression model
  # How would you generalize it?
}

#linear.model(beta=c(0,1,2,3),covariate=X)


linear.model<-function(beta,covariate){
  beta=as.matrix(beta,nrow=length(beta))
  yout=covariate%*%beta[-1]+beta[1]
  return(yout);
}

sum.of.squares<-function(beta,covariate,outcome){
  yout=linear.model(beta=beta,covariate=covariate);
  res=outcome-yout;
  sos= sum(res^2);
  return(sos)
}

sum.of.squares(beta=rep(1,12),covariate=X,outcome=y)
# optim 


fit.linear.model<-function(covariate,outcome){
  X=cbind(1,covariate);
  beta.fit=solve( t(X)%*%X )%*%t(X)%*%outcome;
  return(beta.fit)
}


beta.hat=fit.linear.model(covariate=X,outcome=y)
```

```{r}
calcualte.hat<-function(covariate){
  X=cbind(1,covariate);
  P=X%*%solve(t(X)%*%X)%*%t(X);
  return(P)
}

P=calculate.hat(covariate=X);

resid=y-linear.model(beta=beta.hat,covariate=X);

resid.hat=(diag(length(y))-P)%*%y;

max(abs(resid-resid.hat))


```

```{r}
n=length(y);J=matrix(1,n,n);I=diag(n);
total.sum.of.squares=t(y)%*%(I-J/n)%*%y;
explained.sum.of.squares=t(y)%*%(P-J/n)%*%y;
residual.sum.of.squares=t(y)%*%(I-P)%*%y;


sum.of.squares(beta.hat,covariate=X,outcome=y)

residual.sum.of.squares
```
```{r}

n=100;
set.seed(1)
X=matrix(rnorm(n*4),nrow=n,ncol=4);
y=X%*%c(1,2,3,4)+3+5*rnorm(n);
Z=matrix(rnorm(n*10),nrow=n,ncol=10);

summary(lm(y~X))
summary(lm(y~X+Z))


n=length(y);J=matrix(1,n,n);I=diag(n);
P=calculate.hat(covariate=X);
P.Z=calculate.hat(covariate=cbind(X,Z))

R.sq.adj= 1- ((t(y)%*%(I-P)%*%y)/(n-dim(X)[2]-1)) / ( (t(y)%*%(I-J/n)%*%y)/(n-1));
R.sq.adj

R.sq.adj.Z= 1- ((t(y)%*%(I-P.Z)%*%y)/(n-dim(X)[2]-dim(Z)[2]-1)) / ( (t(y)%*%(I-J/n)%*%y)/(n-1));

R.sq.adj.Z
```
